[package]
name = "apps-info"
version = "0.1.0"
edition = "2021"

[dependencies]
fs2 = "0.4.3"
toml = "0.8.1"

[dependencies.serde]
version = "1.0.188"
features = ["derive"]

[dependencies.reqwest]
version = "0.11.20"
features = ["blocking"]
default-features = false
